version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crud_api_template
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  migrations:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/crud_api_template
    depends_on:
      - db
    command: >
      sh -c "alembic upgrade head"

  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/crud_api_template
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrations

volumes:
  db-data:
